### PR TITLE
Change name, update README, PEP8 cleanup

### PR DESCRIPTION
**Pull request by brianshumate**
I saw in the code where the game is really known as _Neko Atsume 3000_, so I updated the README accordingly. :smile:

### CODE REVIEW

**Comment by SwartzCr** [comment]
honestly I'm fine with a PR that just removes the 3000 from the code :P 
It was a pretty whimsical name to begin with

**Comment by brianshumate** [comment]
How about Neko Atsume 9001? :stuck_out_tongue_winking_eye:

I like the whimsy, but that is fair too. I just wanted the docs to match the game.

**Comment by brianshumate** [comment]
Okay, I dropped the _3000_

**Comment by brianshumate** [comment]
- Dropped the 3000
- Updated the README
- Cleaned up code for PEP8

**Comment by SwartzCr** [comment]
looks good, we should come up with another whimsical name, like 2-bit cats or something, but maybe no numbers

**Pull request merged**
