### PR TITLE
initial colors — addresses #12 (^･o･^)ﾉ”

### PR DESCRIPTION
**Pull request by brianshumate**
Here are some initial colors.

Let me know if anything needs changing or feel free to change colors as you want!

### CODE REVIEW

**Comment by SwartzCr** [comment]
ooh, this is cool!
I was thinking more just having the prefix's be colored - which from looking at the code might just be a re-ordering in that format call? and that way you can tell when you switch between scenes - thoughts?

**Comment by brianshumate** [comment]
:+1: Yeah, let's do that; I'll go ahead and make the changes to this PR

**Comment by brianshumate** [comment]
Okay there are some colors on the labels only now. What do you think?

**Comment by SwartzCr** [comment]
I like it, we'll want more stuff later but this looks good to merge

**Pull request merged**
